image: nbxmpp-master:latest

stages:
  - test
  - build
  - deploy

test-pylint:
  stage: test
  script:
    - python3 .ci/pylint-test.py
    - NBXMPP_EXTERNAL_UNIT_TESTS=1 coverage run --source=nbxmpp -m unittest discover -v
    - coverage report -mi
    - coverage xml -i
    - pip install .
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      coverage_report: 
        coverage_format: cobertura
        path: coverage.xml

build-linux:
  stage: build
  dependencies: []
  script:
    - pip install git+https://dev.gajim.org/gajim/release-helper.git
    - pip install build
    - python3 -m build
    - release-helper build-debian-pkg "$(find dist/nbxmpp-*.tar.gz)" 1 --pkgprefix=python3 --pkgsuffix=nightly

  artifacts:
    name: "nbxmpp-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - dist/nbxmpp-*.tar.gz
      - dist/nbxmpp-*.whl
      - debian_build/python3-nbxmpp*.deb

deploy-pypi:
  stage: deploy
  dependencies:
    - "build-linux"
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - python3 .ci/deploy.py
    - twine upload --username=__token__ --password=$PYPI_TOKEN dist/*
