before_script:
  - sudo apt-get update -qq && sudo apt-get build-dep -y -qq python3-nbxmpp-nightly

stages:
  - test
  - build

run-test:
  stage: test
  script:
    - python3 -m unittest discover -v
    - rm -rf civenv-nbxmpp
    - virtualenv -p python3 --system-site-packages civenv-nbxmpp
    - . ./civenv-nbxmpp/bin/activate
    - pip3 install -I pylint==2.4.4
    - python3 -m pylint nbxmpp --disable=C0103,C0201,C0301,C0325,C0326,C0330,W0201,W0212,W0221,W0231,W0233,W0401,W0601,W0614,W0621,W0622,W1201,R0201,E1101,E1135
    - deactivate
    - rm -rf civenv-nbxmpp

run-build:
  stage: build
  script:
    - rm -rf dist
    - export FN="nbxmpp-"$(date +%F)
    - python3 setup.py sdist
    - scp dist/nbxmpp-*.tar.gz panoramix:/var/www/gajim/downloads/snap/ci/$FN-$CI_COMMIT_SHA.tar.gz

  artifacts:
    name: "nbxmpp-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - dist/nbxmpp-*.tar.gz
