image: nbxmpp-master:latest

stages:
  - test
  - build
  - deploy

test-pylint:
  
  stage: test
  script:
    - python3 .ci/pylint-test.py
    - coverage run --source=nbxmpp -m unittest discover -v
    - coverage report -mi
    - coverage xml -i
    - pip install .
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      coverage_report: 
        coverage_format: cobertura
        path: coverage.xml

build-linux:
  image: nbxmpp-deb-build:latest
  stage: build
  dependencies: []
  script:
    - python3 setup.py sdist bdist_wheel
    - python3 .ci/debian_build.py "$(find dist/nbxmpp-*.tar.gz)" 1 --pkgprefix=python3-

  artifacts:
    name: "nbxmpp-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - dist/nbxmpp-*.tar.gz
      - dist/nbxmpp-*.whl

deploy-pypi:
  stage: deploy
  dependencies:
    - "build-linux"
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - python3 .ci/deploy.py
