before_script:
  - sudo apt-get update -qq && sudo apt-get build-dep -y -qq python3-nbxmpp-nightly

stages:
  - test
  - build

run-test:
  stage: test
  script:
    - rm -rf civenv-nbxmpp
    - virtualenv -p python3 --system-site-packages civenv-nbxmpp
    - . ./civenv-nbxmpp/bin/activate
    - pip3 install -I pylint==2.4.4
    - pip3 install -I coverage
    - pip3 install -I idna
    - pip3 install -I precis-i18n
    - python3 -m pylint nbxmpp --disable=C0103,C0201,C0301,C0326,C0330,W0201,W0212,W0221,W0231,W0233,W0621,W0622,R0201,E1101,E1135
    - coverage run --source=nbxmpp -m unittest discover -v
    - coverage report -mi
    - coverage xml -i
    - deactivate
    - rm -rf civenv-nbxmpp
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      cobertura: coverage.xml

# C0103 invalid-name
# C0201 consider-iterating-dictionary
# C0301 line-too-long
# C0326 bad-whitespace
# C0330 bad-continuation
# W0201 attribute-defined-outside-init
# W0212 protected-access
# W0221 arguments-differ
# W0231 super-init-not-called
# W0233 non-parent-init-called
# W0621 redefined-outer-name
# W0622 redefined-builtin
# R0201 no-self-use
# E1101 no-member
# E1135 unsupported-membership-test

run-build:
  stage: build
  script:
    - rm -rf dist
    - python3 setup.py sdist

  artifacts:
    name: "nbxmpp-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - dist/nbxmpp-*.tar.gz
