image: ci-gajim:master

stages:
  - test
  - build

run-test:
  stage: test
  script:
    - python3 .ci/pylint-test.py
    - coverage run --source=nbxmpp -m unittest discover -v
    - coverage report -mi
    - coverage xml -i
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    reports:
      cobertura: coverage.xml

run-build:
  stage: build
  script:
    - python3 setup.py sdist

  artifacts:
    name: "nbxmpp-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - dist/nbxmpp-*.tar.gz
